### ISSUE TITLE
빌드 실패..!

### ISSUE THREAD

**Issue by 2ssue** [pss407/pss407.github.io#1]
안녕하세요 
잠이 안와서 염탐 시도했다가 빌드 실패로 포스트 업로드 반영이 안돼는게 안타까워서 왔습니다.

jekyll은 중괄호가 안닫혀있으면 컴파일이 안돼서 이런 문장은 피하시는게 좋을 것 같습니다 😥
https://github.com/pss407/pss407.github.io/commit/07487e9bdd8aa2218bda5f0b226c946fd0d502de#diff-e5e66c23fc6579fec1c7e880dbe4e864R50
https://github.com/pss407/pss407.github.io/commit/07487e9bdd8aa2218bda5f0b226c946fd0d502de#diff-e5e66c23fc6579fec1c7e880dbe4e864R52

잘 해결하시길 바랍니다..🙆‍♂️ [Jekyll Docs](https://jekyllrb-ko.github.io/docs/posts/)

**Comment by 2ssue** [comment]
고쳤군요 축하합니다 🎆

**Comment by pss407** [comment]
감사
